twitter:
	name: "origennaku"
	consumer_key: "MkYi53JY8meo9eKJwOOKfZ0GR"
	consumer_secret: "sx8KYQhSuJQNlGf58wHoWT5XbsjZE1Nk68EsEkpUeH0gGNnAAj"
  	access_token: "580490259-9A9jZggowwKvw7H7JuMBPc1QWTFs1mlgQGdslWu9"
  	access_token_secret: "rZmPaE5VNVyMXxDT1fm6IAXoWsXo9AWAhFXPLe0SEaMF5" 