require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProyectsController do

  # This should return the minimal set of attributes required to create a valid
  # Proyect. As you add validations to Proyect, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProyectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all proyects as @proyects" do
      proyect = Proyect.create! valid_attributes
      get :index, {}, valid_session
      assigns(:proyects).should eq([proyect])
    end
  end

  describe "GET show" do
    it "assigns the requested proyect as @proyect" do
      proyect = Proyect.create! valid_attributes
      get :show, {:id => proyect.to_param}, valid_session
      assigns(:proyect).should eq(proyect)
    end
  end

  describe "GET new" do
    it "assigns a new proyect as @proyect" do
      get :new, {}, valid_session
      assigns(:proyect).should be_a_new(Proyect)
    end
  end

  describe "GET edit" do
    it "assigns the requested proyect as @proyect" do
      proyect = Proyect.create! valid_attributes
      get :edit, {:id => proyect.to_param}, valid_session
      assigns(:proyect).should eq(proyect)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Proyect" do
        expect {
          post :create, {:proyect => valid_attributes}, valid_session
        }.to change(Proyect, :count).by(1)
      end

      it "assigns a newly created proyect as @proyect" do
        post :create, {:proyect => valid_attributes}, valid_session
        assigns(:proyect).should be_a(Proyect)
        assigns(:proyect).should be_persisted
      end

      it "redirects to the created proyect" do
        post :create, {:proyect => valid_attributes}, valid_session
        response.should redirect_to(Proyect.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proyect as @proyect" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proyect.any_instance.stub(:save).and_return(false)
        post :create, {:proyect => {}}, valid_session
        assigns(:proyect).should be_a_new(Proyect)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proyect.any_instance.stub(:save).and_return(false)
        post :create, {:proyect => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proyect" do
        proyect = Proyect.create! valid_attributes
        # Assuming there are no other proyects in the database, this
        # specifies that the Proyect created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Proyect.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => proyect.to_param, :proyect => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested proyect as @proyect" do
        proyect = Proyect.create! valid_attributes
        put :update, {:id => proyect.to_param, :proyect => valid_attributes}, valid_session
        assigns(:proyect).should eq(proyect)
      end

      it "redirects to the proyect" do
        proyect = Proyect.create! valid_attributes
        put :update, {:id => proyect.to_param, :proyect => valid_attributes}, valid_session
        response.should redirect_to(proyect)
      end
    end

    describe "with invalid params" do
      it "assigns the proyect as @proyect" do
        proyect = Proyect.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proyect.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyect.to_param, :proyect => {}}, valid_session
        assigns(:proyect).should eq(proyect)
      end

      it "re-renders the 'edit' template" do
        proyect = Proyect.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proyect.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyect.to_param, :proyect => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proyect" do
      proyect = Proyect.create! valid_attributes
      expect {
        delete :destroy, {:id => proyect.to_param}, valid_session
      }.to change(Proyect, :count).by(-1)
    end

    it "redirects to the proyects list" do
      proyect = Proyect.create! valid_attributes
      delete :destroy, {:id => proyect.to_param}, valid_session
      response.should redirect_to(proyects_url)
    end
  end

end
